### ISSUE TITLE
Recreating the file system, previous contents lost!"  ?? -docs , minor

### ISSUE THREAD

**Issue by DG12** [robert-hh/SPI_Flash#1]
In the **README.md** Examples and flashdrive.py 

Should 
`print("Recreate the file system")`
be
`print("Recreating the file system, previous contents lost!")`
?

in **flash.flash_write(addr, buffer)**
 If the address is not a multiple of the page size, the size must not cross a page boundary. 
I am not sure what this means?? 
size of addr = 259, (not a multiple of page size) it **WILL** cross a page boundary 

Should it be 
If size of addr is  not a multiple of the page size<br>
then addr + size of addr  must be within the same page as addr. 
?

Perhaps this would be clearer if you used sector rather than addr.

**Comment by robert-hh** [comment]
Thank you for your comments. It turns out that I changed the code after README.md, such that the note about the relation between the value of addr and write size is not needed any more. For both read and write the buffer size may be larger than the page size.
